# Generated by Django 3.2 on 2022-02-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220218_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_adress1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_adress2',
            new_name='street_address2',
        ),
    ]
